apiVersion: v1
kind: Service
metadata:
  namespace: own-project
  name: nexus
  labels:
    name: nexus
spec:
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30005
  selector:
    name: nexus
  type: NodePort
