apiVersion: v1
kind: Service
metadata:
  namespace: own-project
  name: kibana
  labels:
    name: kibana
spec:
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30006
  selector:
    name: kibana
  type: NodePort
