---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-for-grafana
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
