---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-for-grafana
  namespace: kube-system
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs"
    path: "gv0"
    readOnly: false
