apiVersion: v1
kind: Service
metadata:
  namespace: own-project
  name: murder-tracker
  labels:
    name: murder-tracker
spec:
  ports:
  - port: 8998
    targetPort: 8998
  selector:
    name: murder-tracker
