apiVersion: v1
kind: Service
metadata:
  namespace: own-project 
  name: zabbix-mysql
  labels:
    name: zabbix-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: zabbix-mysql

